blog/urls.py
from django.urls import path
from . import views
from blog.feeds import PostFeed


app_name = 'blog'
urlpatterns = [
    path("", views.index, name='index'),
    path("category/<slug:category_slug>/", views.category, name='category'),
    path("post/<slug:slug>/", views.detail, name="detail"),
    path("search/", views.search, name='search'),
    path("feed/", PostFeed()),
]

"""
Note:
    if the search path comes after thr detail path, 'search/' would be taken as a slug 
    and will result in 404 error
"""

blog1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import BlogSitemap, StaticViewSitemap, CategorySitemap



sitemaps = {
    'static': StaticViewSitemap,
    'blog' : BlogSitemap,
    'category': CategorySitemap,
}


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("python_packages.urls")),
    path("blog/", include("blog.urls")),
    path('subscribe/', include('marketing.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='sitemaps'),

    path('ckeditor/', include('ckeditor_uploader.urls')),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

marketing/urls.py
from django.urls import path
from . import views


app_name = 'marketing'
urlpatterns = [
    path("", views.email_signup, name='subscription'),
]

python_packages/urls.py
from django.urls import path
from . import views

app_name = "python_packages"
urlpatterns = [
    path("", views.index, name="index"),

    path("robots.txt", views.robots, name="robots"),
    path("ads.txt", views.ads, name="ads"),
    path("about/", views.about, name='about'),
    path("contact/", views.contact, name="contact"),
    path("privacy-policy/", views.policy, name="policy"),
    path("affiliate-disclaimer/", views.disclaimer, name="disclaimer"),
]

python_packages/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from ckeditor.fields import RichTextField
from django.utils import timezone


# Create your models here.
class Package(models.Model):
    name = models.CharField(max_length=120, unique=True)
    homepage = models.URLField(blank=True, max_length=300)
    documentation = models.URLField(blank=True, max_length=300)
    affiliate_course = models.URLField(blank=True, max_length=500)
    image = models.ImageField(blank=True, upload_to='package_images')
    description = RichTextUploadingField(blank=True)
    pub_date = models.DateTimeField(default=timezone.now)
    featured = models.BooleanField(default=False)

    def __str__(self):
        return self.name



class Category(models.Model):
    tag = models.CharField(max_length=250, unique=True)
    packages = models.ManyToManyField(Package, blank=True, related_name="categories")

    class Meta:
        ordering = ['id']

    def __str__(self):
        return self.tag

python_packages/views.py
from django.shortcuts import render
from .models import *
from django.http import HttpResponseRedirect
from blog.forms import ContactForm


def index(request):
    categories = Category.objects.all()
    packages = Package.objects.all()
    context = {
        "categories": categories,
        "packages": packages,
    }
    return render(request, "python_packages/index.html", context)


# Contact View
def contact(request):
    new_contact = None

    if request.method == 'POST':
        contact_form = ContactForm(request.POST)
        if contact_form.is_valid():
            contact_form.save()
            new_contact = True

    contact_form = ContactForm()
    context = {
        'title': "Contact",
        'contact_form': contact_form,
        'new_contact': new_contact,
    }

    return render(request, 'python_packages/others/contact.html', context)


# About View
def about(request):
    return render(request, 'python_packages/others/about.html')


def policy(request):
    return render(request, "python_packages/others/policy.html", {})


def disclaimer(request):
    return render(request, "python_packages/others/disclaimer.html", {})


def robots(request):
    return render(request, "python_packages/others/robots.txt", content_type="text/plain")


def ads(request):
    return render(request, "python_packages/others/ads.txt", content_type="text/plain")

python_packages/templates/python_packages/components/footer.html
{% load static %}
    <!-- Footer
    ============================================= -->
    <footer id="footer" class="dark">
        <div class="container">

            <!-- Footer Widgets
            ============================================= -->
            <div class="footer-widgets-wrap">

                <div class="row col-mb-50">
                    <div class="col-lg-8">

                        <div class="row col-mb-50">
                            <div class="col-md-4 mt-0">

                                <div class="widget clearfix">

                                    <p class="mb-3"><strong class="fs-4">PythonStacks</strong></p>

<!--                                    <p>We believe in <strong>Simple</strong>, <strong>Creative</strong> &amp; <strong>Flexible</strong> Design Standards.</p>-->

<!--                                    <div style="background: url('http://themes.semicolonweb.com/html/canvas/images/world-map.png') no-repeat center center; background-size: 100%;">-->
<!--                                        <address>-->
<!--                                            <strong>Headquarters:</strong><br>-->
<!--                                            795 Folsom Ave, Suite 600<br>-->
<!--                                            San Francisco, CA 94107<br>-->
<!--                                        </address>-->
<!--                                        <abbr title="Phone Number"><strong>Phone:</strong></abbr> (1) 8547 632521<br>-->
<!--                                        <abbr title="Fax"><strong>Fax:</strong></abbr> (1) 11 4752 1433<br>-->
<!--                                        <abbr title="Email Address"><strong>Email:</strong></abbr> info@canvas.com-->
<!--                                    </div>-->

                                </div>

                                <div class="d-flex justify-content-center my-5 pl-2 d-none d-md-block">
                                  <a href="https://go.nordvpn.net/aff_c?offer_id=15&aff_id=66092&url_id=902"><img src="{% static 'blog/images/ads/nord_4.png' %}"></a>
                                </div>

                            </div>

                            <div class="col-md-4">

                                <div class="widget widget_links clearfix">

                                    <h4>Pages</h4>

                                    <ul>
                                        <li><a href="{% url 'blog:index' %}">Blog</a></li>
                                        <li><a href="{% url 'python_packages:index' %}">Python Libraries</a></li>
                                        <li><a href="{% url 'python_packages:about' %}">About</a></li>
                                        <li><a href="{% url 'python_packages:contact' %}">Contact</a></li>
                                        <li><a href="{% url 'python_packages:disclaimer' %}">Affiliate Disclaimer</a></li>
                                    </ul>

                                </div>

                            </div>

                            <div class="col-md-4">

                                <div class="widget clearfix">
                                    <h4>Recent Posts</h4>

                                    <div class="posts-sm row col-mb-30" id="post-list-footer">
                                        <div class="entry col-12">
                                            <div class="grid-inner row">
                                                <div class="col">
                                                    <div class="entry-title">
                                                        <h4><a href="#">Lorem ipsum dolor sit amet, consectetur</a></h4>
                                                    </div>
                                                    <div class="entry-meta">
                                                        <ul>
                                                            <li>10th July 2021</li>
                                                        </ul>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="entry col-12">
                                            <div class="grid-inner row">
                                                <div class="col">
                                                    <div class="entry-title">
                                                        <h4><a href="#">Elit Assumenda vel amet dolorum quasi</a></h4>
                                                    </div>
                                                    <div class="entry-meta">
                                                        <ul>
                                                            <li>10th July 2021</li>
                                                        </ul>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="entry col-12">
                                            <div class="grid-inner row">
                                                <div class="col">
                                                    <div class="entry-title">
                                                        <h4><a href="#">Debitis nihil placeat, illum est nisi</a></h4>
                                                    </div>
                                                    <div class="entry-meta">
                                                        <ul>
                                                            <li>10th July 2021</li>
                                                        </ul>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>

                    </div>

                    <div class="col-lg-4">

                        <div class="row col-mb-50">
<!--                            <div class="col-md-4 col-lg-12">-->
<!--                                <div class="widget clearfix" style="margin-bottom: -20px;">-->

<!--                                    <div class="row">-->
<!--                                        <div class="col-lg-6 bottommargin-sm">-->
<!--                                            <div class="counter counter-small"><span data-from="50" data-to="15065421" data-refresh-interval="80" data-speed="3000" data-comma="true"></span></div>-->
<!--                                            <h5 class="mb-0">Total Downloads</h5>-->
<!--                                        </div>-->

<!--                                        <div class="col-lg-6 bottommargin-sm">-->
<!--                                            <div class="counter counter-small"><span data-from="100" data-to="18465" data-refresh-interval="50" data-speed="2000" data-comma="true"></span></div>-->
<!--                                            <h5 class="mb-0">Clients</h5>-->
<!--                                        </div>-->
<!--                                    </div>-->

<!--                                </div>-->
<!--                            </div>-->

                            <div class="col-md-5 col-lg-12">
                                <div class="widget subscribe-widget clearfix">
                                    <h5><strong>Subscribe</strong> to Our Newsletter to get Important News, Amazing Offers &amp; Inside Scoops:</h5>
                                    <div class="widget-subscribe-form-result"></div>
                                    <form id="widget-subscribe-form" action="{% url 'marketing:subscription'  %}" method="post" class="mb-0">
                                        {%csrf_token%}
                                        <div class="input-group mx-auto">
                                            <div class="input-group-text"><i class="icon-email2"></i></div>
                                            <input type="email" id="widget-subscribe-form-email" name="email" class="form-control required email" required placeholder="Enter your Email">
                                            <button class="btn btn-success" type="submit">Subscribe</button>
                                        </div>
                                    </form>
                                </div>
                            </div>

                            <div class="col-12 text-center text-md-start">
                                Copyrights &copy; 2021 | PythonStacks.<br>
                                <div class="copyright-links"><a href="{% url 'python_packages:policy' %}">Privacy Policy</a> / </div>
                                <div class="clear mb-3"></div>

                                <i class="icon-envelope2"></i> info@pythonstacks.com <span class="middot">&middot;</span> <i class="icon-headphones"></i> +233 55-815-1870 <span class="middot">&middot;</span>
                            </div>
<!--                            <div class="col-md-3 col-lg-12">-->
<!--                                <div class="widget clearfix" style="margin-bottom: -20px;">-->

<!--                                    <div class="row">-->
<!--                                        <div class="col-6 col-md-12 col-lg-6 clearfix bottommargin-sm">-->
<!--                                            <a href="#" class="social-icon si-dark si-colored si-facebook mb-0" style="margin-right: 10px;">-->
<!--                                                <i class="icon-facebook"></i>-->
<!--                                                <i class="icon-facebook"></i>-->
<!--                                            </a>-->
<!--                                            <a href="#"><small style="display: block; margin-top: 3px;"><strong>Like us</strong><br>on Facebook</small></a>-->
<!--                                        </div>-->
<!--                                        <div class="col-6 col-md-12 col-lg-6 clearfix">-->
<!--                                            <a href="#" class="social-icon si-dark si-colored si-rss mb-0" style="margin-right: 10px;">-->
<!--                                                <i class="icon-rss"></i>-->
<!--                                                <i class="icon-rss"></i>-->
<!--                                            </a>-->
<!--                                            <a href="#"><small style="display: block; margin-top: 3px;"><strong>Subscribe</strong><br>to RSS Feeds</small></a>-->
<!--                                        </div>-->
<!--                                    </div>-->

<!--                                </div>-->
<!--                            </div>-->

                        </div>

                    </div>
                </div>

            </div><!-- .footer-widgets-wrap end -->

        </div>

    </footer><!-- #footer end -->

python_packages/templates/python_packages/components/nav.html
{% load static %}

<!-- Header
    ============================================= -->
  <header id="header" class="full-header">
      <div id="header-wrap">
          <div class="container">
              <div class="header-row">

                  <!-- Logo
                  ============================================= -->
                  <div id="logo">
                      <a href="{% url 'python_packages:index' %}" class="standard-logo" data-dark-logo="{% static 'python_packages/images/logo.png' %}"><strong class="fs-4">PythonStacks</strong></a>
                      <a href="{% url 'python_packages:index' %}" class="retina-logo" data-dark-logo="images/logo-dark@2x.png"><strong class="fs-5">PythonStacks</strong></a>
                  </div><!-- #logo end -->

                  <div class="header-misc">

                      <!-- Top Search
                      ============================================= -->
                      <div id="top-search" class="header-misc-icon">
                          <a href="#" id="top-search-trigger"><i class="icon-line-search"></i><i class="icon-line-cross"></i></a>
                      </div><!-- #top-search end -->


                  </div>

                  <div id="primary-menu-trigger">
                      <svg class="svg-trigger" viewBox="0 0 100 100"><path d="m 30,33 h 40 c 3.722839,0 7.5,3.126468 7.5,8.578427 0,5.451959 -2.727029,8.421573 -7.5,8.421573 h -20"></path><path d="m 30,50 h 40"></path><path d="m 70,67 h -40 c 0,0 -7.5,-0.802118 -7.5,-8.365747 0,-7.563629 7.5,-8.634253 7.5,-8.634253 h 20"></path></svg>
                  </div>

                  <!-- Primary Navigation
                  ============================================= -->
                  <nav class="primary-menu">

                      <ul class="menu-container">
                          <li class="menu-item">
                              <a class="menu-link" href="{% url 'python_packages:index' %}"><div>Home</div></a>
                          </li>
                          <li class="menu-item">
                              <a class="menu-link" href="{% url 'blog:index' %}"><div>Blog</div></a>
                          </li>
                          <li class="menu-item">
                              <a class="menu-link" href="{% url 'blog:index' %}"><div>Articles</div></a>
                              <ul class="sub-menu-container">
                                  <li class="menu-item">
                                      <a class="menu-link" href="{% url 'blog:category' 'python' %}"><div>Python Tutorials</div></a>
                                  </li>
                                  <li class="menu-item">
                                      <a class="menu-link" href="{% url 'blog:category' 'django' %}"><div>Django Tutorials</div></a>
                                  </li>
                                  <li class="menu-item">
                                      <a class="menu-link" href="{% url 'blog:category' 'software-development' %}"><div>Software Development</div></a>
                                  </li>
                                  <li class="menu-item">
                                      <a class="menu-link" href="{% url 'blog:category' 'ethical-hacking' %}"><div>Ethical Hacking</div></a>
                                  </li>
                              </ul>
                          </li>
                          <li class="menu-item">
                              <a class="menu-link" href="{% url 'blog:category' 'online-courses' %}"><div>Courses</div></a>
                          </li>
                          <li class="menu-item">
                              <a class="menu-link" href="{% url 'python_packages:contact' %}"><div>Contact</div></a>
                          </li>
                          <li class="menu-item">
                              <a class="menu-link" href="https://github.com/janprince" target="_blank">
                                  <i class="icon-github-circled"></i>
                              </a>
                          </li>
                      </ul>

                  </nav><!-- #primary-menu end -->

                  <form class="top-search-form" action="{% url 'blog:search' %}" method="get">
                      <input type="text" name="q" class="form-control" value="" placeholder="Type &amp; Hit Enter.." autocomplete="off">
                  </form>

              </div>
          </div>
      </div>
      <div class="header-wrap-clone"></div>
  </header>

  <!-- #header end -->

python_packages/templates/python_packages/components/newsletter.html
<div class="section section-colored rounded mb-0 px-4">
                  <div class="row justify-content-center align-items-center">
                      <div class="col-lg-5">
                          <h3 class="mb-4 mb-lg-0">Sign up for Updates &amp; Newsletters.</h3>
                      </div>
                      <div class="col-lg-6">
                          <div class="widget subscribe-widget" data-loader="button">

                              <div class="widget-subscribe-form-result"></div>
                              <form id="widget-subscribe-form" action="{% url 'marketing:subscription' %}" method="post" class="mb-0 d-flex">
                                  {% csrf_token %}
                                  <input type="email" id="widget-subscribe-form-email" name="email" required class="form-control form-control-lg not-dark required email" placeholder="Your Email Address">
                                  <button class="button button-large button-black button-dark fw-medium ls0 button-rounded m-0 ms-3" type="submit">Subscribe Now</button>
                              </form>
                          </div>
                      </div>
                  </div>
              </div>